---
title: "dplyr"
author: "TRS"
date: "10/22/2018"
output: html_document
---

```{r}
library(tidyverse)
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv') #read in file from Github

#inspect the data
gapminder #looks at all data
```
##Summary Stats

```{r}
summary(gapminder)
install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) #column names
dim(gapminder) #dimensions
ncol(gapminder) #number of columns
nrow(gapminder) #number of rows
```

##Dplyr

```{r}
filter(gapminder, lifeExp < 29)
```

```{r}
filter(gapminder, country == "Mexico")
```

```{r}
filter(gapminder, country %in% c("Mexico", "Peru"))
```

```{r}
filter(gapminder, country == "Mexico", year == 2002)
```

```{r}
n<- filter(gapminder, country== "Sweden")
n
summary(n)
```

```{r}
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)
gap_cambodia2
```
##simplify select/filter
```{r}
gap_cambodia_new <- gapminder %>% filter(country == "Cambodia") %>% select(-continent, -lifeExp)
gap_cambodia_new
```
##Mutate
```{r}
#adds new variables
gapminder %>% 
  mutate(index = 1:nrow(gapminder))

gapminder %>%
  mutate(gdp = pop*gdpPercap)
```

##Challenge
```{r}
egy_viet <- filter(gapminder, country %in% c("Egypt", "Vietnam"))
egy_viet
mutate(egy_viet,index = 1:nrow(egy_viet))
summary(egy_viet)
max(egy_viet$gdpPercap)
```

##Challenge answer
```{r}
gapminder %>%
  filter(country %in% c("Egypt", "Vietnam")) %>%
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp))
```

##Group by

```{r}
##with mutate()
gap_group <- gapminder %>%
  group_by(country) %>%
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp)) %>%
  ungroup()

##with summarize()
gap_summarize <- gapminder %>%
  group_by(country) %>%
  mutate(gdp = pop * gdpPercap) %>%
  summarize(max_gdp = max(gdp)) %>%
  ungroup()
```

##arrange, arranges columns
```{r}
gap_arrange <- gapminder %>%
  group_by(country) %>%
  mutate(gdp = pop * gdpPercap) %>%
  summarize(max_gdp = max(gdp)) %>%
  ungroup() %>%
  arrange(desc(max_gdp))
```

##Joining
```{r}
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

##explore
co2 %>% head()
co2 %>% dim()

##create a new gapminder variable w/ only 2007 data
gap_2007 <- gapminder %>%
  filter(year == 2007)

##left join w/ co2
lj <- left_join(gap_2007, co2, by = "country")
##another way to write this
lj2 <- gap_2007 %>%
  left_join(co2, by = "country")

##right join
rj <- gap_2007 %>%
  right_join(co2)
```

